# Azure Vote UI control
title: Azure ToDo App
global:
  azure:
    images:
      frontend:
        digest: sha256:6cf5d9916016353e217e036e9985660c27d62aa0c99ef3c71731f8e84084aa73
        image: nodejstodo
        registry: docker.io/magdysalem

      backend:
        digest: sha256:e0b1614551474ee2f3c3ef7c9706b5e19f2107aa36b73c910522af9fa8eb756e
        image: mongo
        registry: docker.io/magdysalem

# MongoDB Admin
mongoDBAdmin: admin
mongoDBPassword: password26

# Service controls
serviceType: LoadBalancer
appFrontLabel: todoapp
appBackLabel: mongodb

#ingressName
clusterDNS: ""

# how many frontends do we want?
replicaFrontCount: 1
replicaBackCount: 1

## Where it will be deployed
nameSpace: contoso
