# Azure Vote UI control
title: Azure ToDo App
global:
  azure:
    billingIdentifier: DONOTMODIFY
    images:
      frontend:
        digest: << ADD digest >>
        image: todojs
        registry: << Add ACR server name >>
      backend:
        digest: << ADD digest >>
        image: mongo
        registry: << Add ACR server name >>
# MongoDB Admin


# Service controls
serviceType: LoadBalancer
appFrontLabel: todoapp
appBackLabel: mongodb
#ingressName
clusterDNS: ""

# how many frontends do we want?
replicaFrontCount: 1
replicaBackCount: 1

## Where it will be deployed
nameSpace: << enter namespace i.e contoso >>









